services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn surgicalm.backend.wsgi:application --bind 0.0.0.0:8000 --workers 2 --timeout 60
    expose:
      - "8000" 
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - redis

  nginx: 
    image: nginx:stable-alpine
    depends_on:
      - web 
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped