services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD} 
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn surgicalm.backend.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - db 

volumes:
  mysql_data: