services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn surgicalm.backend.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - DATABASE_HOST=host.docker.internal
      - DATABASE_PORT=3307