# docker-compose.prod.yml

services:
  web:

  celery-worker:
    build: .
    command: >
      sh -c "
        export PYTHONPATH=/app &&
        export DJANGO_SETTINGS_MODULE=backend.settings &&
        cd surgicalm &&
        celery -A surgicalm.celeryapp worker --loglevel=info --concurrency=2
      "
    env_file:
      - .env
    depends_on:
      - redis
      - db

  nginx:
    ports:
      - "80:80" 
      - "443:443" 
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/api.surgicalm.com:/etc/letsencrypt/live/api.surgicalm.com:ro
      - /etc/letsencrypt/archive/api.surgicalm.com:/etc/letsencrypt/archive/api.surgicalm.com:ro