# Generated by Django 5.0.1 on 2024-07-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_category_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_1', models.BooleanField(default=False)),
                ('video_2', models.BooleanField(default=False)),
                ('video_3', models.BooleanField(default=False)),
                ('video_4', models.BooleanField(default=False)),
                ('video_5', models.BooleanField(default=False)),
                ('video_6', models.BooleanField(default=False)),
            ],
        ),
    ]
