# Generated by Django 5.0.7 on 2024-08-17 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_generalvideos_uservideorefresh_remove_video_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_time', models.IntegerField()),
                ('week', models.IntegerField()),
                ('mon', models.IntegerField()),
                ('tues', models.IntegerField()),
                ('wed', models.IntegerField()),
                ('thur', models.IntegerField()),
                ('fri', models.IntegerField()),
                ('sat', models.IntegerField()),
                ('sun', models.IntegerField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_collection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
