# Generated by Django 5.0.7 on 2024-08-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_datacollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollection',
            name='all_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='fri',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='mon',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='sat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='sun',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='thur',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='tues',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='wed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='week',
            field=models.IntegerField(default=0),
        ),
    ]
