# Generated by Django 4.2.5 on 2024-08-24 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_datacollection_all_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_1', models.BooleanField(default=False)),
                ('video_2', models.BooleanField(default=False)),
                ('video_3', models.BooleanField(default=False)),
                ('video_4', models.BooleanField(default=False)),
                ('video_5', models.BooleanField(default=False)),
                ('video_6', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
