# Generated by Django 4.2.5 on 2024-08-24 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_modulecompletion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulecompletion',
            name='user',
        ),
        migrations.AddField(
            model_name='modulecompletion',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
