# Generated by Django 4.2.5 on 2024-08-24 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_modulecompletion_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulecompletion',
            name='video_6',
        ),
    ]
