# Generated by Django 4.2.5 on 2024-08-24 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_modulecompletion_video_6'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulecompletion',
            old_name='video_1',
            new_name='Affirmation',
        ),
        migrations.RenameField(
            model_name='modulecompletion',
            old_name='video_2',
            new_name='Breathing',
        ),
        migrations.RenameField(
            model_name='modulecompletion',
            old_name='video_3',
            new_name='Exercise',
        ),
        migrations.RenameField(
            model_name='modulecompletion',
            old_name='video_4',
            new_name='Meditation',
        ),
        migrations.RenameField(
            model_name='modulecompletion',
            old_name='video_5',
            new_name='Yoga',
        ),
    ]
