# Generated by Django 4.2.5 on 2024-08-25 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_video_1_modulecompletion_affirmation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_1', models.IntegerField(default=0)),
                ('video_2', models.IntegerField(default=0)),
                ('video_3', models.IntegerField(default=0)),
                ('video_4', models.IntegerField(default=0)),
                ('video_5', models.IntegerField(default=0)),
                ('video_6', models.IntegerField(default=0)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnglewoodBreast', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='SpecialVideo',
        ),
    ]
