# Generated by Django 4.2.5 on 2024-08-25 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_specialassignment_specialcategories_specialvideos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSpecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_1', models.IntegerField(default=0)),
                ('video_2', models.IntegerField(default=0)),
                ('video_3', models.IntegerField(default=0)),
                ('video_4', models.IntegerField(default=0)),
                ('video_5', models.IntegerField(default=0)),
                ('video_6', models.IntegerField(default=0)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
