# Generated by Django 4.2.5 on 2024-08-27 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_delete_specialassignment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralVideos',
            new_name='GeneralModules',
        ),
        migrations.RenameModel(
            old_name='AssignmentSpecial',
            new_name='SpecialAssign',
        ),
        migrations.RenameModel(
            old_name='SpecialVideos',
            new_name='SpecialModule',
        ),
    ]
