# Generated by Django 4.2.5 on 2024-08-27 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_generalvideos_generalmodules_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyModuleCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnglewoodBreast_Cat', models.CharField(max_length=100)),
                ('EnglewoodBreast_Sub', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EnglewoodBreastCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(default='N/A', max_length=100)),
                ('sub1', models.CharField(max_length=100)),
                ('sub2', models.CharField(max_length=100)),
                ('sub3', models.CharField(max_length=100)),
                ('sub4', models.CharField(max_length=100)),
                ('sub5', models.CharField(max_length=100)),
                ('sub6', models.CharField(max_length=100)),
                ('sub7', models.CharField(max_length=100)),
                ('sub8', models.CharField(max_length=100)),
                ('sub9', models.CharField(max_length=100)),
                ('sub10', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='generalmodules',
            old_name='category',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='generalmodules',
            old_name='title',
            new_name='Title',
        ),
        migrations.AddField(
            model_name='generalmodules',
            name='Sub',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SpecialTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_1', models.IntegerField(default=0)),
                ('video_2', models.IntegerField(default=0)),
                ('video_3', models.IntegerField(default=0)),
                ('video_4', models.IntegerField(default=0)),
                ('video_5', models.IntegerField(default=0)),
                ('video_6', models.IntegerField(default=0)),
                ('video_7', models.IntegerField(default=0)),
                ('video_8', models.IntegerField(default=0)),
                ('video_9', models.IntegerField(default=0)),
                ('video_10', models.IntegerField(default=0)),
                ('video_11', models.IntegerField(default=0)),
                ('video_12', models.IntegerField(default=0)),
                ('video_13', models.IntegerField(default=0)),
                ('video_14', models.IntegerField(default=0)),
                ('video_15', models.IntegerField(default=0)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
