# Generated by Django 4.2.5 on 2024-08-28 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_dailymodulecategories_englewoodbreastcategories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalmodules',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='generalmodules',
            old_name='Title',
            new_name='title',
        ),
    ]
