# Generated by Django 4.2.5 on 2024-08-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_category_generalmodules_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulecompletion',
            name='Affirmation',
        ),
        migrations.RemoveField(
            model_name='modulecompletion',
            name='Breathing',
        ),
        migrations.RemoveField(
            model_name='modulecompletion',
            name='Exercise',
        ),
        migrations.RemoveField(
            model_name='modulecompletion',
            name='Meditation',
        ),
        migrations.RemoveField(
            model_name='modulecompletion',
            name='Yoga',
        ),
    ]
