# Generated by Django 4.2.5 on 2024-08-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_modulecompletion_affirmation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englewoodbreastcategories',
            name='sub1',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='englewoodbreastcategories',
            name='sub10',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='englewoodbreastcategories',
            name='sub2',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='englewoodbreastcategories',
            name='sub3',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='englewoodbreastcategories',
            name='sub4',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='englewoodbreastcategories',
            name='sub5',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='englewoodbreastcategories',
            name='sub6',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='englewoodbreastcategories',
            name='sub7',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='englewoodbreastcategories',
            name='sub8',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='englewoodbreastcategories',
            name='sub9',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
