# Generated by Django 4.2.5 on 2024-08-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_englewoodbreastcategories_sub1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='englewoodbreastcategories',
            name='icon',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
