# Generated by Django 5.1.1 on 2024-09-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_englewoodbreastcategories_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulecompletion',
            name='pos_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modulecompletion',
            name='pos_10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modulecompletion',
            name='pos_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modulecompletion',
            name='pos_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modulecompletion',
            name='pos_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modulecompletion',
            name='pos_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modulecompletion',
            name='pos_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modulecompletion',
            name='pos_7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modulecompletion',
            name='pos_8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modulecompletion',
            name='pos_9',
            field=models.IntegerField(default=0),
        ),
    ]
