# Generated by Django 5.1.1 on 2024-09-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_modulecompletion_pos_1_modulecompletion_pos_10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quote', models.CharField(max_length=1000)),
            ],
        ),
    ]
