# Generated by Django 5.1.1 on 2024-09-21 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_englewoodbreasttasks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TesterModel',
        ),
    ]
