# Generated by Django 5.1.1 on 2024-09-30 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_assignspecial_englewoodbreasttaskstracker_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignSpecial',
        ),
    ]
