# Generated by Django 5.1.1 on 2024-10-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_delete_assignspecial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalmodules',
            name='description',
            field=models.CharField(default='N/A', max_length=500),
        ),
    ]
