# Generated by Django 5.1.1 on 2024-10-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_generalmodules_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialmodule',
            name='description',
            field=models.CharField(default='N/A', max_length=500),
        ),
    ]
