# Generated by Django 5.1.1 on 2024-10-07 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_specialmodule_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialtracker',
            name='patient',
        ),
        migrations.DeleteModel(
            name='SpecialAssign',
        ),
        migrations.DeleteModel(
            name='SpecialTracker',
        ),
    ]
