# Generated by Django 5.1.1 on 2024-10-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_remove_specialtracker_patient_delete_specialassign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalmodules',
            name='description',
            field=models.TextField(),
        ),
    ]
