# Generated by Django 5.1.1 on 2025-01-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_assignedtasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtasks',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
