# Generated by Django 5.1.1 on 2025-01-22 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_assignedtasks_iscompleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uservideorefresh',
            old_name='user',
            new_name='patient',
        ),
    ]
