# Generated by Django 5.1.1 on 2025-02-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_rename_user_uservideorefresh_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerHospitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='modulecompletion',
            name='patient',
        ),
        migrations.DeleteModel(
            name='EnglewoodBreastTasksTracker',
        ),
        migrations.DeleteModel(
            name='ModuleCompletion',
        ),
    ]
