# Generated by Django 5.1.1 on 2025-02-06 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_partnerhospitals_remove_modulecompletion_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.partnerhospitals'),
        ),
    ]
