# Generated by Django 5.1.1 on 2025-02-07 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_customuser_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.partnerhospitals')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleSubcategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=255)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.modulecategories')),
            ],
        ),
    ]
