# Generated by Django 5.1.1 on 2025-02-07 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_modulecategories_modulesubcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulesubcategories',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.partnerhospitals'),
        ),
    ]
