# Generated by Django 5.1.1 on 2025-02-08 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_moduleslist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=100)),
                ('taskDesc', models.CharField(max_length=100)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.partnerhospitals')),
            ],
        ),
        migrations.DeleteModel(
            name='EnglewoodBreastTasks',
        ),
        migrations.RemoveField(
            model_name='dailymodulecategories',
            name='EnglewoodBreast_Cat',
        ),
        migrations.RemoveField(
            model_name='dailymodulecategories',
            name='EnglewoodBreast_Sub',
        ),
        migrations.AddField(
            model_name='dailymodulecategories',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.modulecategories'),
        ),
        migrations.AddField(
            model_name='dailymodulecategories',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.partnerhospitals'),
        ),
        migrations.AddField(
            model_name='dailymodulecategories',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.modulesubcategories'),
        ),
        migrations.AddField(
            model_name='moduleslist',
            name='hospital',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.partnerhospitals'),
        ),
        migrations.AlterField(
            model_name='assignedmodules',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.moduleslist'),
        ),
        migrations.AlterField(
            model_name='assignedquotes',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.quotes'),
        ),
        migrations.AlterField(
            model_name='assignedtasks',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.tasklist'),
        ),
    ]
