# Generated by Django 5.1.1 on 2025-02-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_tasklist_delete_englewoodbreasttasks_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnglewoodBreastCategories',
        ),
        migrations.DeleteModel(
            name='GeneralModules',
        ),
        migrations.AlterField(
            model_name='moduleslist',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='moduleslist',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
