# Generated by Django 5.1.1 on 2025-02-08 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_delete_englewoodbreastcategories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedtasks',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='assignedtasks',
            name='task',
        ),
        migrations.CreateModel(
            name='AssignedQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.quotes')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isCompleted', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.tasklist')),
            ],
        ),
        migrations.DeleteModel(
            name='AssignedQuotes',
        ),
        migrations.DeleteModel(
            name='AssignedTasks',
        ),
    ]
