# Generated by Django 5.1.1 on 2025-02-08 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_remove_assignedtasks_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedtask',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='assignedtask',
            name='task',
        ),
        migrations.DeleteModel(
            name='AssignedQuote',
        ),
        migrations.DeleteModel(
            name='AssignedTask',
        ),
    ]
