# Generated by Django 5.1.1 on 2025-02-11 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_assignedquote_assignedtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedmodules',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.moduleslist'),
        ),
        migrations.AlterField(
            model_name='assignedquote',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.quotes'),
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tasklist'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.partnerhospitals'),
        ),
        migrations.AlterField(
            model_name='dailymodulecategories',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.modulecategories'),
        ),
        migrations.AlterField(
            model_name='dailymodulecategories',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.partnerhospitals'),
        ),
        migrations.AlterField(
            model_name='dailymodulecategories',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.modulesubcategories'),
        ),
        migrations.AlterField(
            model_name='modulecategories',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.partnerhospitals'),
        ),
        migrations.AlterField(
            model_name='moduleslist',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.modulecategories'),
        ),
        migrations.AlterField(
            model_name='moduleslist',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.partnerhospitals'),
        ),
        migrations.AlterField(
            model_name='moduleslist',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.modulesubcategories'),
        ),
        migrations.AlterField(
            model_name='modulesubcategories',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.modulecategories'),
        ),
        migrations.AlterField(
            model_name='modulesubcategories',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.partnerhospitals'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='Quote',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.partnerhospitals'),
        ),
        migrations.AddConstraint(
            model_name='modulecategories',
            constraint=models.UniqueConstraint(fields=('hospital', 'category', 'icon'), name='unique_per_hospital'),
        ),
        migrations.AddConstraint(
            model_name='modulesubcategories',
            constraint=models.UniqueConstraint(fields=('category', 'subcategory'), name='unique_subcategory_per_category'),
        ),
    ]
