# Generated by Django 5.1.1 on 2025-02-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_alter_assignedmodules_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='Quote',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
