# Generated by Django 5.1.1 on 2025-02-12 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_alter_quotes_quote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpecialCategories',
        ),
        migrations.DeleteModel(
            name='SpecialModule',
        ),
        migrations.DeleteModel(
            name='TrackSpecial',
        ),
    ]
