# Generated by Django 5.1.6 on 2025-02-21 23:01

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_delete_specialcategories_delete_specialmodule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2025, 2, 21))),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.modulecategories')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.partnerhospitals')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.modulesubcategories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
