# Generated by Django 5.1.6 on 2025-02-21 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_watcheddata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchedData',
        ),
    ]
