# Generated by Django 4.2.5 on 2025-02-24 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_alter_watcheddata_date_pushnotificationtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushNotificationToken',
        ),
    ]
