# Generated by Django 5.1.6 on 2025-02-27 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_pushnotificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='icon',
            field=models.CharField(default='alarm-outline', max_length=255),
        ),
        migrations.AlterField(
            model_name='watcheddata',
            name='date',
            field=models.DateField(default=datetime.date(2025, 2, 27)),
        ),
    ]
