# Generated by Django 5.2 on 2025-05-18 09:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_tasklist_icon_alter_watcheddata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watcheddata',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='PushNotificationToken',
        ),
    ]
