# Generated by Django 5.2 on 2025-05-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_cascade_blacklistedtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataCollection',
        ),
    ]
