# Generated by Django 5.2 on 2025-05-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_delete_datacollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleslist',
            name='media_type',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio')], default='video', max_length=5),
        ),
    ]
