# Generated by Django 5.2 on 2025-08-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0066_moduleslist_media_type'),
    ]

    operations = [
        # Manually add this RunSQL operation for FULLTEXT index
        migrations.RunSQL(
            sql="ALTER TABLE users_customuser ADD FULLTEXT INDEX user_search_idx (username, email);",
            reverse_sql="ALTER TABLE users_customuser DROP INDEX user_search_idx;"
        ),
        
        # The following AddIndex operations were auto-generated by Django
        migrations.AddIndex(
            model_name='assignedmodules',
            index=models.Index(fields=['patient', 'isCompleted'], name='users_assig_patient_c387e6_idx'),
        ),
        migrations.AddIndex(
            model_name='assignedtask',
            index=models.Index(fields=['patient', 'isCompleted'], name='users_assig_patient_7b8997_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['hospital', 'user_type'], name='users_custo_hospita_d2bc4a_idx'),
        ),
        migrations.AddIndex(
            model_name='watcheddata',
            index=models.Index(fields=['user', 'date'], name='users_watch_user_id_a21bb5_idx'),
        ),
    ]
